"""add user profile fields

Revision ID: 5b8c3c8b5c67
Revises: 77bdede724d0
Create Date: 2026-04-24 19:54:49.917230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b8c3c8b5c67'
down_revision: Union[str, Sequence[str], None] = '77bdede724d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skipping identity column alter on task_completions.id — Supabase uses
    # GENERATED ALWAYS AS IDENTITY which requires DROP IDENTITY, not DROP DEFAULT.
    # BIGINT vs Integer is compatible and safe to leave as-is.
    op.alter_column('task_completions', 'completed_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_task_completions_completed_at'), table_name='task_completions')
    op.drop_index(op.f('idx_task_completions_task_id'), table_name='task_completions')
    op.create_index(op.f('ix_task_completions_completed_date'), 'task_completions', ['completed_date'], unique=False)
    op.create_index(op.f('ix_task_completions_id'), 'task_completions', ['id'], unique=False)
    op.create_unique_constraint(None, 'task_completions', ['task_id', 'completed_date'])
    op.drop_constraint(op.f('task_completions_task_id_fkey'), 'task_completions', type_='foreignkey')
    op.create_foreign_key(None, 'task_completions', 'tasks', ['task_id'], ['id'])
    op.drop_column('task_completions', 'created_at')
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('tasks', 'completed')
    op.drop_column('tasks', 'last_completed_at')
    op.alter_column('users', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'language',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               nullable=False,
               existing_server_default=sa.text('\'"en"\'::text'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('\'"en"\'::text'))
    op.alter_column('users', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("''::text"))
    op.add_column('tasks', sa.Column('last_completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('task_completions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_completions', type_='foreignkey')
    op.create_foreign_key(op.f('task_completions_task_id_fkey'), 'task_completions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'task_completions', type_='unique')
    op.drop_index(op.f('ix_task_completions_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completed_date'), table_name='task_completions')
    op.create_index(op.f('idx_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    op.create_index(op.f('idx_task_completions_completed_at'), 'task_completions', [sa.literal_column('completed_date DESC')], unique=False)
    op.alter_column('task_completions', 'completed_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # Skipping identity column restore — see upgrade() comment.
    # ### end Alembic commands ###
